services:
  - type: web
    name: ai-marketing-consultant
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: CARTESIA_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: LIVEKIT_URL # The wss://... URL for your LiveKit project
        sync: false
      - key: PYTHON_VERSION
        value: 3.11
